name: .NET Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Update this if you're using a different .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Install Playwright Browsers
        run: pwsh bin/Debug/net9.0/playwright.ps1 install

      - name: Run Tests
        run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
